### ISSUE TITLE
Use Python logging library

### ISSUE THREAD

**Issue by benjwadams** [ioos/sensorml2iso#24]
The log level does not appear configurable at the moment, and the application generates a large amount of logs/stdout during a typical run against an SOS instance with a decent amount of data. 

Statements like the following generate more info than is really needed for anything but development users and should probably correspond to `INFO` or `DEBUG` level logs instead:
https://github.com/ioos/sensorml2iso/blob/master/sensorml2iso/sensorml2iso.py#L537-L538

 Furthermore, by default the Docker installation writes the stdout from the application into the container's /var/log directory, which is not presently on a volume by default.

**Comment by mwengren** [comment]
Hey @benjwadams  I traced this issue through a little today finally.  

There is already a way to configure the logging in sensorml2iso (not fine tuned via a logging library), but just by using the --verbose flag passed at the command line.   I had to delve into the Docker [code](https://github.com/ioos/sensorml2iso/blob/master/contrib/init/51_config) a bit, but I noticed that the way it was written, --verbose flag is always passed and it isn't tunable in the [config.json](https://github.com/ioos/sensorml2iso/blob/master/contrib/config/config.json) file.   I added, I think, the option to specify `verbose: true|false` in config.json.  

I don't have an easy way to test this, but can you look at the changes I made in this fork(https://github.com/mwengren/sensorml2iso/commits/docker_fix), and if you think they are ok try to build the Docker images off of it and see if the verbose flag is skipped and the output is reduced in those containers? 

This seems like an easier fix than going back and changing the logging code in the module if it works.

**Comment by benjwadams** [comment]
@mwengren, looked at the branch and looks good.  Could you please make a PR and I'll merge into master.

**Comment by benjwadams** [comment]
Closing for now due to merging of #25
