### ISSUE TITLE
NDBC SOS, problems with CSW search filtering and SOS GetObservation scheme references

### ISSUE THREAD

**Issue by emiliom** [ioos/sensorml2iso#26]
*(copied from https://github.com/ioos/catalog/issues/63, where this issue started. See that issue for a complete discussion and background. I'll copy here a few of the comments from there)*

NDBC station records are presenting several problems on IOOS Catalog CSW searches (and some of those problems are also apparent on the IOOS Catalog application). I suspect these problems are long standing, but I can't say for sure. There are 2 broad problems, with some overlap:

1. **CSW search filtering:**
    a. A CSW search that includes an OGC FES datetime filter invariably fails to produce any NDBC station records.
    b. For observed properties or parameters, CF standard names are not exposed. A search using CF standard name literals fails in most or possibly all cases. A different, eyeball-friendly (and often machine unfriendly) set of parameter names is exposed via subject terms: Water Temperature, Air Temperature, Ocean Currents, etc. In addition, sensor urn's rather than observedProperty parameter names (which are largely CF standard names) are incorrectly exposed.
2. **The SOS GetObservation sample/template urls returned in the scheme references list** has two mistakes that lead to errors when issuing requests:
    a. observedProperty should use CF standard names, not sensor urn's as shown *(8/3/2018 correction: the NDBC SOS accepts parameter names or corresponding mmisw url's, but 4 out of the 9 parameters listed are actually not CF standard names.)*
    b. eventTime iso8601 datetime strings must include a Z (UTC) suffix

See the [NDBC SOS documentation page](https://sdf.ndbc.noaa.gov/sos/) for reference and working examples.

I've prepared a [Jupyter notebook illustrating all these problems and solutions](http://nbviewer.jupyter.org/gist/emiliom/8d75e50c1ab76375771d62156619e2dc) (when known). No solution or workaround is known for problem 1.a.

---------------------------------------------------------------

`eventTime` **is supported** by NDBC. But it seems to require a "Z" UTC suffix after each datetime string. (I don't remember if the i52nsos and ncsos servers are more forgiving and flexible; they probably are)

---------------------------------------------------------------

After going over previous comments, the NDBC SOS docs and responses, and the `sensorml2iso` code, I think all these problems are resolvable within `sensorml2iso`. But it'll take a good chunk of effort.

Briefly, the least disruptive strategy will be to implement the `sos_type` argument for "ndbc", and use it to extract station['starting'], station['ending'] and station['variables'] from the `GetCapabilities` offering instead of SensorML. The GetCapabilities response is already available in `sensorml2iso` in the `sosgc` object.

For problem 2.b ("b. eventTime iso8601 datetime strings must include a Z (UTC) suffix"), we simply add the Z suffix in https://github.com/ioos/sensorml2iso/blob/master/sensorml2iso/sensorml2iso.py#L412 and https://github.com/ioos/sensorml2iso/blob/master/sensorml2iso/sensorml2iso.py#L422 if `sos_type == "ndbc"`. It's very likely that a Z suffix won't impact other SOS types, but adding it only for ndbc would be the most cautious approach.

**Comment by emiliom** [comment]
@mwengren I've applied all the changes I was planning, and tested on my local dev code using this command (on one station):

```bash
sensorml2iso -s http://sdf.ndbc.noaa.gov/sos/server.php --stations=urn:ioos:station:wmo:plsf1 --sos_type=ndbc --response_formats='text/csv'
```

[Here's the ISO XML it generated.](https://gist.github.com/emiliom/67d5ff87d2379932f0037e735d109d63) Can you take a look to double check that this XML record would solve the problems we've discussed? I think it does.

I haven't looked at your old `ndbc_sos_handling` branch yet. I implemented a pretty simple `sos_type` handling scheme that just tests for "ndbc" to do a few special processing steps, and handles all other `sos_type` entries (including the default None) the same way as before.

-------------------------------------------------------------

@mwengren Thanks for your review! Great.

Some quick follow ups:

>  so hopefully it resolves all the issues you found? It looks to me to resolve the timeExtent and proper GetObs URL at least, didn't check the others.

Yup, as far as I can tell it resolves all the issues I identified.

> I looked at your code and looks good, but you may want to check out this commit to add the sos_type parameter read to command_line.py since I didn't see that in your branch yet - but maybe you just haven't pushed that part yet.

While I haven't looked at that commit yet, the `sos_type` parameter read was already in the code base master branch. It just wasn't being actively used. See https://github.com/ioos/sensorml2iso/blob/master/sensorml2iso/command_line.py#L51

I'll work on fuller testing next, hopefully today.

-------------------------------------------------------------

> Can you run against the full NDBC SOS and make sure it completes successfully and doesn't error out? We need the master branch to be able to produce a full WAF for Catalog, so it's essential to test all stations in the SOS in case there are edge cases your code might miss. There will be errors for stations that failed in the logs if you run it with --verbose flag, but some are expected because not all their DescribeSensor URLs are functional (errors internal to their service), but it should dump out a folder with ~1800 XML records if successful. It will print a list of failed stations at the end of the log output with --verbose on.

I ran it on the NDBC SOS w/o selecting a specific set of stations, using this statement:
```bash
sensorml2iso --sos_type=ndbc -s http://sdf.ndbc.noaa.gov/sos/server.php --response_formats='text/csv' --verbose
```

It generated 1,008 station ISO XML files (not 1,800). The log file is pretty big (7.5 MB), mainly due to the DescribeSensor XML being copied there. Near the beginning, after listing all stations, it lists 23 stations that I assume did not generate an ISO XML, and had this error message:
```
SOS DescribeSensor error returned for: <station urn>, skipping. Error msg: No data found for this station
```
These are listed again towards the end, preceded by this message: "Stations in 'failures' list (should match DescribeSensor errors):"

I haven't looked at the XML files.

I also ran it against the NANOOS SOS, and everything seems fine. I only did a quick inspection of one of the XML files, and it looked fine.

**Comment by mwengren** [comment]
@emiliom Looks good, as I mentioned in ioos/catalog#63.  Let's see about merging the PR.

**Comment by emiliom** [comment]
Great! Hopefully there won't be big surprises.

Thanks for the new release. That was fast!

I'll go ahead and close this issue, since as far as we can tell it's been addressed. I suggest we leave https://github.com/ioos/catalog/issues/63 open until these updates propagate to the catalog and we can fully confirm that the CSW problems are also solved.

**Comment by mwengren** [comment]
Ok, it is available in conda-forge as well (thanks to their nifty auto-building):
```
conda list -n IOOS sensorml2iso
packages in environment at C:\Working\local\python\Miniconda2\envs\IOOS:

sensorml2iso              1.0.4                      py_0    conda-forge
```
