### ISSUE TITLE
"NDBC" commit introduced an eventTime string bug?

### ISSUE THREAD

**Issue by emiliom** [ioos/sensorml2iso#28]
I'm guessing the recent, latest release of sensorml2iso is now being used to generate iso metadata records for NOS-COOPS, based on tests starting yesterday (8/20). It looks like [my "NDBC" PR](https://github.com/ioos/sensorml2iso/pull/27) actually introduced a bug in the GetObservation `eventTime` string for non-NDBC service endpoints!

This is what a current NOS-COOPS GetObservation link looks like, taken from the IOOS Catalog:
```
http://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS?eventTime=2018-08-19T16:12:49None/2018-08-19T18:12:49None&request=GetObservation&version=1.0.0&responseFormat=text/csv&offering=urn:ioos:station:NOAA.NOS.CO-OPS:9087096&service=SOS&observedProperty=http://mmisw.org/ont/cf/parameter/sea_water_temperature
```

The `eventTime` arguments have an aberrant "None" string at the end of each datetime:  `2018-08-19T16:12:49None/2018-08-19T18:12:49None`. Previously there was no timezone suffix after the datetime, and this argument would've looked like this: `2018-08-19T16:12:49/2018-08-19T18:12:49`.

I *think* the fix is simple, and involves changing [this line](https://github.com/ioos/sensorml2iso/blob/master/sensorml2iso/sensorml2iso.py#L424):
```python
utc_code = 'Z' if self.sos_type.lower() == 'ndbc' else None
```
to
```python
utc_code = 'Z' if self.sos_type.lower() == 'ndbc' else ''
```

But I haven't tested it, and won't have time at least till mid Wednesday.

**Comment by mwengren** [comment]
Resolved by #29.
