### ISSUE TITLE
NDBC SOS is still not properly parsed for GetObs request

### ISSUE THREAD

**Issue by mwengren** [ioos/sensorml2iso#9]
InvalidParameterValue is returned for both 'observedProperty' and 'eventTime' currently.

'observedProperty' is a valid parameter, but sensorml2iso is requesting a stationID rather than a parameter - due to content of SensorML in NDBC service not being consistent with others.  

'eventTime' is not supported by NDBC and need to handle as an edge case.  Example exception:

```
<ows:Exception exceptionCode="InvalidParameterValue" locator="observedProperty">
<ows:ExceptionText>urn:ioos:sensor:wmo:51204::watertemp1</ows:ExceptionText>
</ows:Exception>

<ows:Exception exceptionCode="InvalidParameterValue" locator="eventTime">
<ows:ExceptionText>2017-01-26T03:03:20/2017-01-26T05:03:20</ows:ExceptionText>
</ows:Exception>

<ows:Exception exceptionCode="InvalidParameterValue" locator="eventTime">
<ows:ExceptionText>2017-01-26T03:03:20/2017-01-26T05:03:20</ows:ExceptionText>
</ows:Exception>
```

**Comment by emiliom** [comment]
As I work on preparing a PR following up on https://github.com/ioos/catalog/issues/63, should we reuse this issue, including changing its title to cover the broader scope? Or open a new issue and close this one?

**Comment by mwengren** [comment]
@emiliom You can close this one and create a new one with the full issue list you uncovered.  This one I just wanted to record the errors I saw somewhere when first testing NDBC SOS.

**Comment by emiliom** [comment]
Thanks. Closing.
